# Generated by Django 4.1.7 on 2023-03-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('RoomId', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('available', models.IntegerField()),
                ('type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
