steps:


# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'europe-west4-docker.pkg.dev/$PROJECT_ID/frontendrepo/front:$SHORT_SHA'
  - '.'

# This step pushes the image to Artifact Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'europe-west4-docker.pkg.dev/$PROJECT_ID/frontendrepo/front:$SHORT_SHA'


  #europe-west4-docker.pkg.dev/vivid-cargo-380519/frontendrepo