# Generated by Django 4.1.7 on 2023-03-07 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='maneger', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=50)),
                ('maxrooms', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
