# Generated by Django 4.1.7 on 2023-03-06 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='id',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='maneger', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
