# Generated by Django 4.1.7 on 2023-03-06 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(blank=True)),
                ('number_days', models.IntegerField()),
                ('is_canceled', models.BooleanField(default=False)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='Rooms.room')),
            ],
        ),
    ]
