# Generated by Django 4.1.7 on 2023-03-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('reservationId', models.AutoField(primary_key=True, serialize=False)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(blank=True)),
                ('number_days', models.IntegerField()),
                ('is_canceled', models.BooleanField(default=False)),
            ],
        ),
    ]
