apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django
spec:
  selector:
    matchLabels:
      app: django-app
  replicas: 1
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: hmzahkml/atypon-fnal:latest
          envFrom:
            - configMapRef:
                name: django-env

---

apiVersion: v1
kind: Service
metadata:
  name: my-django-service
spec:
  type: LoadBalancer
  selector:
    app: react-app
  ports:
    - name: my-app
      port: 3001
      targetPort: 8000